[package]
name = "deathframe"
version = "0.0.0"
authors = ["Noah Rosenzweig <rosenzweig.noah@gmail.com>"]
edition = "2018"
description = "My game development framework for the amethyst game engine"

[dependencies]
amethyst   = "0.10.0"
regex      = "1.1.5"
serde      = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
