[package]
name = "deathframe"
version = "0.5.1"
authors = ["Noah Rosenzweig <rosenzweig.noah@gmail.com>"]
edition = "2018"
description = "My game development framework for the amethyst game engine"
license = "MIT"
repository = "https://github.com/Noah2610/deathframe"

[workspace]
members = [
    "deathframe_physics",
]

[dependencies.physics]
package = "deathframe_physics"
path = "./deathframe_physics"
optional = true

[dependencies.amethyst]
version = "0.14.0"
default-features = false
features = ["animation", "audio", "renderer"]

[dependencies.serde]
version = "1.0.104"
features = ["derive"]
optional = true

[features]
default = []

vulkan = ["amethyst/vulkan"]
metal  = ["amethyst/metal"]
empty  = ["amethyst/empty"]

# physics = []

nightly = ["amethyst/nightly"]
