[package]
name = "deathframe"
version = "0.5.1"
authors = ["Noah Rosenzweig <rosenzweig.noah@gmail.com>"]
edition = "2018"
description = "My game development framework for the amethyst game engine"
license = "MIT"
repository = "https://github.com/Noah2610/deathframe"

[dependencies]
serde = { version = "1.0.89", features = ["derive"], optional = true }
# bitflags = "=1.0.4"  # https://github.com/rust-lang/rust/issues/59134#issuecomment-489430178

[dependencies.amethyst]
version = "0.14.0"
default-features = false
features = ["animation", "audio", "renderer"]

[features]
default = []

vulkan = ["amethyst/vulkan"]
metal  = ["amethyst/metal"]
empty  = ["amethyst/empty"]

nightly = ["amethyst/nightly"]
